from __future__ import annotations

import json
from typing import Any

import yaml

from agents_sync.claude_io import read_markdown
from agents_sync.state import SourceItem, slugify


READ_ONLY_TOOLS = {"Read", "Grep", "Glob", "LS"}
WRITE_TOOLS = {"Write", "Edit", "MultiEdit", "NotebookEdit"}


def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def yaml_frontmatter(data: dict[str, Any]) -> str:
    return yaml.safe_dump(data, allow_unicode=True, sort_keys=False).strip()


def normalize_list(value: Any) -> list[str]:
    if value is None:
        return []
    if isinstance(value, str):
        return [item.strip() for item in value.split(",") if item.strip()]
    if isinstance(value, list):
        return [str(item).strip() for item in value if str(item).strip()]
    return [str(value).strip()]


def tool_base_name(tool: str) -> str:
    return tool.split("(", 1)[0].strip()


def infer_codex_sandbox(frontmatter: dict[str, Any]) -> str | None:
    tools = {tool_base_name(t) for t in normalize_list(frontmatter.get("tools"))}
    denied = {tool_base_name(t) for t in normalize_list(frontmatter.get("disallowedTools"))}
    if tools and tools <= READ_ONLY_TOOLS:
        return "read-only"
    if denied & WRITE_TOOLS:
        return "read-only"
    return None


def render_codex_agent(source: SourceItem) -> str:
    doc = read_markdown(source.source_path)
    name = slugify(str(doc.frontmatter.get("name") or source.source_path.stem))
    description = str(
        doc.frontmatter.get("description") or f"Converted Claude Code agent: {name}"
    ).strip()
    instructions = doc.body or "Follow the role and task scope described above."
    preserved = {
        key: value
        for key, value in doc.frontmatter.items()
        if key not in {"name", "description"}
    }
    if preserved:
        instructions += "\n\n---\nConverted Claude-specific metadata for manual review:\n"
        instructions += json.dumps(preserved, indent=2, ensure_ascii=False, sort_keys=True)
    lines = [
        "# Generated by agents-sync. Edit the Claude source, not this file.",
        f"# Source: {source.source_path}",
        f"# Source SHA256: {source.digest}",
        f"name = {toml_string(name)}",
        f"description = {toml_string(description)}",
    ]
    sandbox = infer_codex_sandbox(doc.frontmatter)
    if sandbox:
        lines.append(f"sandbox_mode = {toml_string(sandbox)}")
    model = doc.frontmatter.get("model")
    if isinstance(model, str) and model not in {"inherit", "sonnet", "opus", "haiku"}:
        lines.append(f"model = {toml_string(model)}")
    effort = doc.frontmatter.get("effort")
    if isinstance(effort, str) and effort in {"low", "medium", "high"}:
        lines.append(f"model_reasoning_effort = {toml_string(effort)}")
    lines.append(f"developer_instructions = {toml_string(instructions)}")
    lines.append("")
    return "\n".join(lines)


def render_codex_skill(source: SourceItem) -> str:
    source_skill_md = source.source_path / "SKILL.md"
    doc = read_markdown(source_skill_md)
    name = slugify(str(doc.frontmatter.get("name") or source.logical_name))
    description = str(
        doc.frontmatter.get("description") or f"Converted Claude Code skill: {name}"
    ).strip()
    preserved = {
        key: value
        for key, value in doc.frontmatter.items()
        if key not in {"name", "description"}
    }
    parts = [
        "---",
        yaml_frontmatter({"name": name, "description": description}),
        "---",
        "",
        "<!-- Generated by agents-sync. Edit the Claude source, not this file. -->",
        f"<!-- Source: {source_skill_md} -->",
        f"<!-- Source tree SHA256: {source.digest} -->",
        "",
        doc.body.strip(),
    ]
    if preserved:
        parts.extend(
            [
                "",
                "---",
                "",
                "## Converted Claude-specific metadata for manual review",
                "",
                "```json",
                json.dumps(preserved, indent=2, ensure_ascii=False, sort_keys=True),
                "```",
            ]
        )
    return "\n".join(parts).rstrip() + "\n"
