"""Codex .toml and SKILL.md parse / render.

Phase 3 adds parse functions so changes on the Codex side can be folded
back into the canonical and propagated to the Claude side.
"""
from __future__ import annotations

import io
import json
import re
import tomllib
from typing import Any

from ruamel.yaml import YAML


READ_ONLY_TOOLS = {"Read", "Grep", "Glob", "LS"}
WRITE_TOOLS = {"Write", "Edit", "MultiEdit", "NotebookEdit"}

PAIR_ID_RE = re.compile(r'^pair_id\s*=\s*"([^"]+)"', re.MULTILINE)
_CORRUPTED_UTF8_BOM = "\u00ef\u00bb\u00bf"

KNOWN_CODEX_TOML_KEYS = {
    "pair_id",
    "name",
    "description",
    "developer_instructions",
    "sandbox_mode",
    "model",
    "model_reasoning_effort",
}

# v0.1 used to append a JSON metadata blob to developer_instructions; strip it
# on parse so adopted v0.1 artifacts don't leak the marker into canonical.body.
_LEGACY_REVIEW_MARKER = "\n\n---\nConverted Claude-specific metadata for manual review:"


def _make_yaml() -> YAML:
    yml = YAML(typ="rt")
    yml.preserve_quotes = True
    yml.width = 4096
    yml.indent(mapping=2, sequence=4, offset=2)
    return yml


def _yaml_dump(data: Any) -> str:
    buf = io.StringIO()
    _make_yaml().dump(data, buf)
    return buf.getvalue()


def _normalize_toml_text(text: str) -> str:
    if text.startswith("\ufeff"):
        return text[1:]
    # Defensive handling for already-corrupted BOM bytes rendered as text.
    if text.startswith(_CORRUPTED_UTF8_BOM):
        return text[3:]
    return text


def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def tool_base_name(tool: str) -> str:
    return tool.split("(", 1)[0].strip()


def infer_codex_sandbox(tools: list[str], disallowed_tools: list[str]) -> str | None:
    base_tools = {tool_base_name(t) for t in tools if t}
    base_denied = {tool_base_name(t) for t in disallowed_tools if t}
    if base_tools and base_tools <= READ_ONLY_TOOLS:
        return "read-only"
    if base_denied & WRITE_TOOLS:
        return "read-only"
    return None


def extract_pair_id(toml_text: str) -> str | None:
    toml_text = _normalize_toml_text(toml_text)
    match = PAIR_ID_RE.search(toml_text)
    return match.group(1) if match else None


def _strip_legacy_review_metadata(body: str) -> str:
    idx = body.find(_LEGACY_REVIEW_MARKER)
    return body[:idx] if idx >= 0 else body


# ---------- agent ----------

def render_codex_agent_toml(canonical: dict[str, Any]) -> str:
    name = canonical["name"]
    description = canonical.get("description", "")
    instructions = canonical.get("body", "")

    lines = [
        "# Generated by agents-sync. Edit the canonical document or the Claude source.",
        f"pair_id = {toml_string(canonical['pair_id'])}",
        f"name = {toml_string(name)}",
    ]
    if description:
        lines.append(f"description = {toml_string(description)}")

    sandbox = canonical.get("per_agentic_tool_only", {}).get("codex", {}).get(
        "sandbox_mode"
    ) or infer_codex_sandbox(
        canonical.get("tools", []),
        canonical.get("disallowed_tools", []),
    )
    if sandbox:
        lines.append(f"sandbox_mode = {toml_string(sandbox)}")

    model = canonical.get("model")
    if isinstance(model, str) and model not in {"inherit", "sonnet", "opus", "haiku"}:
        lines.append(f"model = {toml_string(model)}")

    effort = canonical.get("effort")
    if isinstance(effort, str) and effort in {"low", "medium", "high"}:
        lines.append(f"model_reasoning_effort = {toml_string(effort)}")

    for key, value in sorted(
        canonical.get("per_agentic_tool_extra", {}).get("codex", {}).items()
    ):
        if isinstance(value, str):
            lines.append(f"{key} = {toml_string(value)}")
        elif isinstance(value, bool):
            lines.append(f"{key} = {'true' if value else 'false'}")
        elif isinstance(value, (int, float)):
            lines.append(f"{key} = {value}")
        # complex types deferred until they appear in the wild

    if instructions:
        lines.append(f"developer_instructions = {toml_string(instructions)}")
    lines.append("")
    return "\n".join(lines)


def parse_codex_agent_toml(text: str, prior_canonical: dict[str, Any] | None = None) -> dict[str, Any]:
    """Parse a Codex agent .toml into a canonical dict.

    If `prior_canonical` is given, per-agentic-tool state for other agentic tools
    (e.g. claude) survives untouched.
    """
    from agents_sync.canonical import empty_canonical, new_pair_id

    text = _normalize_toml_text(text)
    data = tomllib.loads(text)
    if not isinstance(data, dict):
        raise ValueError("Codex agent TOML must be a table at root")

    canonical = dict(prior_canonical) if prior_canonical else empty_canonical("agent")

    if "name" in data:
        canonical["name"] = str(data["name"])
    if "description" in data:
        canonical["description"] = str(data["description"])
    if "developer_instructions" in data:
        canonical["body"] = _strip_legacy_review_metadata(str(data["developer_instructions"]))
    if "model" in data:
        canonical["model"] = data["model"]
    if "model_reasoning_effort" in data:
        canonical["effort"] = data["model_reasoning_effort"]

    per_agentic_tool_only = dict(canonical.get("per_agentic_tool_only") or {})
    codex_only = dict(per_agentic_tool_only.get("codex", {}))
    if "sandbox_mode" in data:
        codex_only["sandbox_mode"] = data["sandbox_mode"]
    per_agentic_tool_only["codex"] = codex_only
    canonical["per_agentic_tool_only"] = per_agentic_tool_only

    per_agentic_tool_extra = dict(canonical.get("per_agentic_tool_extra") or {})
    per_agentic_tool_extra["codex"] = {
        key: value
        for key, value in data.items()
        if key not in KNOWN_CODEX_TOML_KEYS
    }
    canonical["per_agentic_tool_extra"] = per_agentic_tool_extra

    if "pair_id" in data:
        canonical["pair_id"] = str(data["pair_id"])
    elif prior_canonical is None:
        canonical["pair_id"] = new_pair_id()

    return canonical


# ---------- skill ----------

def render_codex_skill_md(canonical: dict[str, Any]) -> str:
    """Render the SKILL.md file for the Codex side of a skill pair.

    No leading auto-comment is emitted so that parsing the rendered file
    back into a canonical is a clean fixed point (NFR-06).
    """
    frontmatter = {"pair_id": canonical["pair_id"], "name": canonical["name"]}
    if canonical.get("description"):
        frontmatter["description"] = canonical["description"]

    body = canonical.get("body", "").strip()

    parts = [
        "---",
        _yaml_dump(frontmatter).rstrip(),
        "---",
        "",
        body,
    ]
    return "\n".join(parts).rstrip() + "\n"


def parse_codex_skill_md(text: str, prior_canonical: dict[str, Any] | None = None) -> dict[str, Any]:
    """Parse a Codex skill SKILL.md into a canonical dict."""
    from agents_sync.canonical import empty_canonical, new_pair_id
    from agents_sync.claude_io import FRONTMATTER_RE, _yaml_load

    match = FRONTMATTER_RE.match(text)
    if match is None:
        frontmatter_data: dict[str, Any] = {}
        body = text.strip()
    else:
        raw, body_raw = match.groups()
        body = body_raw.strip()
        loaded = _yaml_load(raw)
        if loaded is None:
            frontmatter_data = {}
        elif not isinstance(loaded, dict):
            raise ValueError("Codex SKILL.md frontmatter must be a YAML mapping")
        else:
            frontmatter_data = dict(loaded)

    canonical = dict(prior_canonical) if prior_canonical else empty_canonical("skill")
    canonical["body"] = body

    if "name" in frontmatter_data:
        canonical["name"] = str(frontmatter_data["name"])
    if "description" in frontmatter_data:
        canonical["description"] = str(frontmatter_data["description"])

    per_agentic_tool_extra = dict(canonical.get("per_agentic_tool_extra") or {})
    per_agentic_tool_extra["codex"] = {
        key: value
        for key, value in frontmatter_data.items()
        if key not in {"pair_id", "name", "description"}
    }
    canonical["per_agentic_tool_extra"] = per_agentic_tool_extra

    if "pair_id" in frontmatter_data:
        canonical["pair_id"] = str(frontmatter_data["pair_id"])
    elif prior_canonical is None:
        canonical["pair_id"] = new_pair_id()

    return canonical
