"""Codex .toml rendering and lightweight pair_id extraction.

Phase 2 only renders Codex output (no parser); the canonical is the
source of truth. Phase 3 will add a TOML parser for reverse projection
and adoption of foreign Codex artifacts.
"""
from __future__ import annotations

import io
import json
import re
from typing import Any

from ruamel.yaml import YAML


READ_ONLY_TOOLS = {"Read", "Grep", "Glob", "LS"}
WRITE_TOOLS = {"Write", "Edit", "MultiEdit", "NotebookEdit"}

PAIR_ID_RE = re.compile(r'^pair_id\s*=\s*"([^"]+)"', re.MULTILINE)


def _make_yaml() -> YAML:
    yml = YAML(typ="rt")
    yml.preserve_quotes = True
    yml.width = 4096
    yml.indent(mapping=2, sequence=4, offset=2)
    return yml


def _yaml_dump(data: Any) -> str:
    buf = io.StringIO()
    _make_yaml().dump(data, buf)
    return buf.getvalue()


def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def tool_base_name(tool: str) -> str:
    return tool.split("(", 1)[0].strip()


def infer_codex_sandbox(tools: list[str], disallowed_tools: list[str]) -> str | None:
    base_tools = {tool_base_name(t) for t in tools if t}
    base_denied = {tool_base_name(t) for t in disallowed_tools if t}
    if base_tools and base_tools <= READ_ONLY_TOOLS:
        return "read-only"
    if base_denied & WRITE_TOOLS:
        return "read-only"
    return None


def extract_pair_id(toml_text: str) -> str | None:
    match = PAIR_ID_RE.search(toml_text)
    return match.group(1) if match else None


def render_codex_agent_toml(canonical: dict[str, Any]) -> str:
    name = canonical["name"]
    description = canonical.get("description") or f"Converted Claude Code agent: {name}"
    instructions = canonical.get("body") or "Follow the role and task scope described above."

    lines = [
        "# Generated by agents-sync. Edit the canonical document or the Claude source.",
        f"pair_id = {toml_string(canonical['pair_id'])}",
        f"name = {toml_string(name)}",
        f"description = {toml_string(description)}",
    ]

    sandbox = canonical.get("codex_only", {}).get("sandbox_mode") or infer_codex_sandbox(
        canonical.get("tools", []),
        canonical.get("disallowed_tools", []),
    )
    if sandbox:
        lines.append(f"sandbox_mode = {toml_string(sandbox)}")

    model = canonical.get("model")
    if isinstance(model, str) and model not in {"inherit", "sonnet", "opus", "haiku"}:
        lines.append(f"model = {toml_string(model)}")

    effort = canonical.get("effort")
    if isinstance(effort, str) and effort in {"low", "medium", "high"}:
        lines.append(f"model_reasoning_effort = {toml_string(effort)}")

    for key, value in sorted(canonical.get("codex_extra", {}).items()):
        if isinstance(value, str):
            lines.append(f"{key} = {toml_string(value)}")
        elif isinstance(value, bool):
            lines.append(f"{key} = {'true' if value else 'false'}")
        elif isinstance(value, (int, float)):
            lines.append(f"{key} = {value}")
        # complex passthrough types are deferred to Phase 3 when Codex
        # parsing lands and the structure is known.

    lines.append(f"developer_instructions = {toml_string(instructions)}")
    lines.append("")
    return "\n".join(lines)


def render_codex_skill_md(canonical: dict[str, Any]) -> str:
    """Render the SKILL.md file for the Codex side of a skill pair."""
    frontmatter = {
        "pair_id": canonical["pair_id"],
        "name": canonical["name"],
        "description": canonical.get("description")
        or f"Converted Claude Code skill: {canonical['name']}",
    }

    parts = [
        "---",
        _yaml_dump(frontmatter).rstrip(),
        "---",
        "",
        "<!-- Generated by agents-sync. Edit the canonical or the Claude source. -->",
        "",
        canonical.get("body", "").strip(),
    ]
    return "\n".join(parts).rstrip() + "\n"
